services:
  minio:
    image: quay.io/minio/minio:${VERSION:-latest}
    command: server /data --console-address ":9100"
    ports:
      - 9000:9000
      - 9100:9100
    volumes:
      - minio_data:/data
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER:-admin}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD:-myp@ssw0rd}
      - MINIO_BROWSER_REDIRECT_URL=${SCHEME:-https}://${DOMAIN_CONSOLE:?}
      - MINIO_SERVER_URL=${SCHEME:-https}://${DOMAIN:-minio.localhost}
    healthcheck:
      test: ["CMD", "mc", "ready", "local"]
      interval: 5s
      timeout: 5s
      retries: 5
volumes:
  minio_data:
