services:
  nexus:
    image: "sonatype/nexus3:3.58.0"
    restart: always
    volumes:
      - "nexus-data:/nexus-data"
    ports:
      - 8123:8123
      - 8081:8081
      - 8082:8082

volumes:
  nexus-data:
