services:
  nexus:
    image: "sonatype/nexus3:latest"
    restart: always
    volumes:
      - "nexus-data:/nexus-data"
    ports:
      - 8123:8123
      - 8081:8081
      - 8082:8082
      - 8083:8083

volumes:
  nexus-data:
