services:
  phpldapadmin:
    image: osixia/phpldapadmin:latest
    container_name: phpldapadmin
    environment:
      PHPLDAPADMIN_LDAP_HOSTS: ${PHPLDAPADMIN_LDAP_HOSTS}
      PHPLDAPADMIN_HTTPS: ${PHPLDAPADMIN_HTTPS:-false}
    ports:
      - "8389:80"
