services:
  registry-cache:
    image: registry:${VERSION:-2}
    restart: always
    environment:
      REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY: /var/lib/registry
      REGISTRY_PROXY_REMOTEURL: https://registry-1.docker.io
    volumes:
      - registry-cache:/var/lib/registry
    ports:
      - 5000:5000

volumes:
  registry-cache:
